In [1]:
import numpy as np
import pandas as pd

PIVOT TABLES #use to create heat map  
#if we want to use use your row,col or values which are not present in data we can add them using pivot table

In [ ]:


data = {
    'Date':pd.date_range('2023-01-01',periods=20),
    'Product':['A','B','C','D'] * 5,
    'Region':['East','West','North','South',
              'East','West','North','South',
              'East','West','North','South',
              'East','West','North','South',
              'East','West','North','South',
              ],
    'Sales':np.random.randint(100,1000,20),
    'Units':np.random.randint(10,100,20),
    'Rep':['John','Mary','Bob','Alice',
           'John','Mary','Bob','Alice',
           'John','Mary','Bob','Alice',
           'John','Mary','Bob','Alice',
           'John','Mary','Bob','Alice'],       

}
df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quater'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quater
0  2023-01-01       A   East    404     55   John  January     Q1
1  2023-01-02       B   West    717     21   Mary  January     Q1
2  2023-01-03       C  North    764     17    Bob  January     Q1
3  2023-01-04       D  South    622     61  Alice  January     Q1
4  2023-01-05       A   East    630     59   John  January     Q1
5  2023-01-06       B   West    410     14   Mary  January     Q1
6  2023-01-07       C  North    853     89    Bob  January     Q1
7  2023-01-08       D  South    123     87  Alice  January     Q1
8  2023-01-09       A   East    868     35   John  January     Q1
9  2023-01-10       B   West    165     72   Mary  January     Q1
10 2023-01-11       C  North    423     22    Bob  January     Q1
11 2023-01-12       D  South    230     95  Alice  January     Q1
12 2023-01-13       A   East    614     53   John  January     Q1
13 2023-01-14       B   West    459     88   Mary  January     Q1
14 2023-01-15       C  North    590     62    Bob  January     Q1
15 2023-01-16       D  South    842     94  Alice  January     Q1
16 2023-01-17       A   East    837     71   John  January     Q1
17 2023-01-18       B   West    517     74   Mary  January     Q1
18 2023-01-19       C  North    278     94    Bob  January     Q1
19 2023-01-20       D  South    342     53  Alice  January     Q1

In [10]:
#creating data frames using pivot tables
pd.pivot_table(df,values="Sales",index='Region',columns="Product",aggfunc='median')

Product      A      B      C      D
Region
East     630.0    NaN    NaN    NaN
North      NaN    NaN  590.0    NaN
South      NaN    NaN    NaN  342.0
West       NaN  459.0    NaN    NaN

In [11]:
pivot2 = pd.pivot_table(df,values=['Sales','Units'],index='Region',columns="Product")
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     670.6    NaN    NaN    NaN  54.6   NaN   NaN   NaN
North      NaN    NaN  581.6    NaN   NaN   NaN  56.8   NaN
South      NaN    NaN    NaN  431.8   NaN   NaN   NaN  78.0
West       NaN  453.6    NaN    NaN   NaN  53.8   NaN   NaN

PIVOT TABLES:  It is used in aggregation

CROSS TABS:   It is used in counting purpose

CROSS TABS

In [ ]:
pd.crosstab(df['Region'],df['Product']) # it gives the count

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0